# frozen_string_literal: true

require_relative 'endpoint_helper'

recurring_donation_designations = @client.recurring_donation_designations(1_150_348)
print_recurring_donation_designations(recurring_donation_designations)
